// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Beie4s7cuUa_GAsVQX_YdDx0q6qjrj8',
    appId: '1:308303504367:web:357fcf8e6be70268a20c1a',
    messagingSenderId: '308303504367',
    projectId: 'calling-a6e56',
    authDomain: 'calling-a6e56.firebaseapp.com',
    storageBucket: 'calling-a6e56.firebasestorage.app',
    measurementId: 'G-11W0R8MLEM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99P6NfSsBVU4XqmMEjK4qvJk0fzI9qQ0',
    appId: '1:308303504367:android:d19c97f2e0b0a746a20c1a',
    messagingSenderId: '308303504367',
    projectId: 'calling-a6e56',
    storageBucket: 'calling-a6e56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkCNj4vIylIS-xTrJ38dzZkebZZPswFAk',
    appId: '1:308303504367:ios:034abc24ffe0685ea20c1a',
    messagingSenderId: '308303504367',
    projectId: 'calling-a6e56',
    storageBucket: 'calling-a6e56.firebasestorage.app',
    iosBundleId: 'com.example.callLeadsApp',
  );

}